# Generated by Django 2.2 on 2020-09-13 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortur', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myurl',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='myurl',
            name='shortcode',
            field=models.CharField(blank=True, max_length=18, unique=True),
        ),
    ]
