# Generated by Django 2.2 on 2020-09-12 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortur', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myurl',
            name='shortcode',
            field=models.CharField(default='amancfecode', max_length=18, unique=True),
            preserve_default=False,
        ),
    ]
