# Generated by Django 2.2 on 2020-09-18 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortur', '0002_auto_20200913_1217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myurl',
            name='shortcode',
            field=models.CharField(blank=True, max_length=15, unique=True),
        ),
    ]
